### ISSUE TITLE
input observation vector in testKalman.m

### ISSUE THREAD

**Issue by naruya** [melihaltun/KalmanFilter3D#1]
Hi, I believe this line should be `k_z = [x_n(k); y_n(k); z_n(k)];` . What do you think?
(I am not very familiar with Matlab, so I apologize if I'm mistaken.)

https://github.com/melihaltun/KalmanFilter3D/blob/566eb3899071dde57a3260fa59cafc6525abc623/testKalman.m#L34

**Comment by melihaltun** [comment]
You are right. Observations have to be obtained from noise added inputs. I will update the script. Thanks for catching it.

**Comment by melihaltun** [comment]
Fixed!

**Comment by melihaltun** [comment]
https://github.com/melihaltun/KalmanFilter3D/commit/bd89145f45bc438a74044ef430d536cfb6429dd4
